apiVersion: v1
kind: Pod
metadata:
  name: pod-pending
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "10Gi"
        cpu: "4"